// This file is auto-generated by TanStack Router
// Do not edit this file manually

import { Route as rootRoute } from "./routes/__root"
import { Route as NewsletterRoute } from "./routes/newsletter"
import { Route as HomeRoute } from "./routes/home"
import { Route as ExploreRoute } from "./routes/explore"
import { Route as CollectionRoute } from "./routes/collection"
import { Route as IndexRoute } from "./routes/index"

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    "/collection": {
      preLoaderRoute: typeof CollectionRoute
      parentRoute: typeof rootRoute
    }
    "/explore": {
      preLoaderRoute: typeof ExploreRoute
      parentRoute: typeof rootRoute
    }
    "/home": {
      preLoaderRoute: typeof HomeRoute
      parentRoute: typeof rootRoute
    }
    "/newsletter": {
      preLoaderRoute: typeof NewsletterRoute
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren([IndexRoute, CollectionRoute, ExploreRoute, HomeRoute, NewsletterRoute])
